FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
EXPOSE 8080
EXPOSE 8081
WORKDIR /src

COPY . .
WORKDIR /src/Metalurgica.Web
RUN dotnet restore Metalurgica.Web.csproj

RUN dotnet build Metalurgica.Web.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish Metalurgica.Web.csproj -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY Metalurgica.Web/nginx.conf /etc/nginx/nginx.conf
