events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    types {
        application/wasm wasm;
    }

    server {
        listen       8080;
        server_name  localhost;

        index index.html;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html =404;
        }
    }
}
