FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

COPY ../ ./

RUN dotnet restore

RUN dotnet publish -c Release -o out
RUN dotnet dev-certs https --trust
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /runtime
COPY --from=build-env /app/out .

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT ["dotnet", "Metalurgica.Api.dll"]